# Generated by Django 6.0.6 on 2026-07-07 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_student_admission_date_student_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('exam_date', models.DateField()),
                ('total_marks', models.IntegerField()),
                ('obtained_marks', models.IntegerField()),
                ('grade', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=5)),
                ('result', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
