# Generated by Django 6.0.6 on 2026-07-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('General', 'General'), ('Examination', 'Examination'), ('Holiday', 'Holiday'), ('Placement', 'Placement'), ('Event', 'Event'), ('Admission', 'Admission')], max_length=50)),
                ('description', models.TextField()),
                ('notice_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notice/')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
